### ISSUE TITLE
Expo/React Native unable to import JSON when published

### ISSUE THREAD

**Issue by zachrussell12** [axa-group/nlp.js#1135]
**Describe the bug**

I have a React Native app I created using Expo. When running the app off my computer and viewing it on my IOS device, node-nlp-rn works as intended. I am able to create the model, use it, as well as re-train it. Unfortunately though, whenever I use 

`expo publish`

to publish my app to Expo's servers and use on my phone without having to be connected to my local WiFi nlp.js does not work as intended. It seems to export to JSON to be saved in Async Storage just fine, but upon importing it to be used it throws this promise rejection: 

`[Unhandled promise rejection: TypeError: undefined is not a constructor (evaluating 'new BaseNLU.classes[obj.className]()')]
at http://192.168.1.89:19000/node_modules%5Cexpo%5CAppEntry.bundle
platform=ios&dev=true&hot=false&minify=false:243651:50 in <unknown>
at http://192.168.1.89:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:243650:40 in fromObj
at http://192.168.1.89:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:244111:47 in <unknown>
at http://192.168.1.89:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:244106:47 in fromObj
at http://192.168.1.89:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:244475:31 in fromObj
at http://192.168.1.89:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:244495:20 in _import
at dataHandlers\neuralNW.js:27:32 in AsyncStorage.getItem.then$argument_0
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:294:29 in invoke
at node_modules\regenerator-runtime\runtime.js:63:36 in tryCatch
at node_modules\regenerator-runtime\runtime.js:155:27 in invoke
at node_modules\regenerator-runtime\runtime.js:190:16 in PromiseImpl$argument_0
at node_modules\react-native\node_modules\promise\setimmediate\core.js:45:6 in tryCallTwo
at node_modules\react-native\node_modules\promise\setimmediate\core.js:200:22 in doResolve
at node_modules\react-native\node_modules\promise\setimmediate\core.js:66:11 in Promise
at node_modules\regenerator-runtime\runtime.js:189:15 in callInvokeWithMethodAndArg
at node_modules\regenerator-runtime\runtime.js:212:38 in enqueue
at node_modules\regenerator-runtime\runtime.js:239:8 in exports.async
at http://192.168.1.89:19000/node_modules%5Cexpo%5CAppEntry.bundle?platform=ios&dev=true&hot=false&minify=false:193359:47 in _callee2
at node_modules\react-native\node_modules\promise\setimmediate\core.js:37:13 in tryCallOne
at node_modules\react-native\node_modules\promise\setimmediate\core.js:123:24 in setImmediate$argument_0
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:130:14 in _callTimer
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:181:14 in _callImmediatesPass
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:441:30 in callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:387:6 in __callImmediates
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:135:6 in __guard$argument_0
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:364:10 in __guard
at node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:134:4 in flushedQueue`

This only happens when the app is not running off my local computer, when it is it works perfectly fine.

**To Reproduce**
1. Create a React Native app using Expo
2. Import node-nlp-rn
3. Write code to create a simple model when ran
4. Run expo publish in console
5. Build the model on the published version of the app

**Expected behavior**
node-nlp-rn should work properly on both instances of the React Native app.

**Desktop (please complete the following information):**
 - OS: Coding in VS on Windows, Running App on IOS
 - Browser: None
 - Package version: node-nlp-rn@3.5.2
 - Node version: v16.14.2

**Comment by zachrussell12** [comment]
**I believe I have temporarily fixed this problem.**

For anyone that was having the same issue above here's what I did to resolve it in my case, this may not work for you. For that reason, any original code I tell you to edit I have you comment out the original code so you'll have it just in case something goes wrong:

1. Go to the following file path: node-nlp-rn/lib/nlu/base-nlu.js
2. In that file find the fromObj function
3. In that function, comment out this line:
    `const instance = new BaseNLU.classes[obj.className]();`
4. Add the following line below it:
     `const instance = new BaseNLU.classes["BrainNLU]();`
    From my testing, the published version of the RN app was pulling the class name from somewhere else, in my case it 
    thought the class name was the single letter F.
5. Now go to the following file path: node-nlp-rn/lib/classifiers/classifier.js
6. In that file find the fromObj function
7. In that function, comment out this line:
     `const instance = new Classifier.classes[obj.className]();`
8. Add the following line below it:
     `const instance = new Classifier.classes["BrainClassifier"]();`
    Again from my testing, the published version of the RN app was pulling the class name from somewhere else, in my case it 
    thought the class name for this function was the single lower-case letter b.

After these steps I created a fresh NLP model and it works perfectly now both on my local computer and the published version. With the way my code is written, it doesn't seem to affect its ability at all and is properly re-trainable without any problems.

**Comment by ericzon** [comment]
hello @zachrussell12 thanks for commenting this issue and adding the steps to make it work but would you mind to create a minimal repo with an small example to reproduce the error?

**Comment by aigloss** [comment]
Closing due to inactivity. Please, re-open if you think the topic is still alive.

**Comment by omerbrandis** [comment]
Hi,

I'm experiencing the same issue on the newest versions of node-nlp
Installed node-nlp ( v5 alpha ) a few wreks ago. Managed to train and process under node.js.
Tried today to use node-nlp-rn.
Getting the error : typeError: basenlu.classes[obj.className] is not a constructor.

Tried folowing the instructions for modifing the two fromObject functions  , it had no effect.
Maybe i misunderstood the last step "create a fresh nlp model" which i dont understand and didnt do.
(Running under nextjs)
