### ISSUE TITLE
text.split is not a function in tokenizer

### ISSUE THREAD

**Issue by mesin** [axa-group/nlp.js#209]
**Describe the bug**
Processing message is failing

Happens when context is used:

```
const context = new ConversationContext({});
result = await nlpManager.process(message, context);
```

 - Version latest master (3.2.0)

**Additional context**
```
Trained (hr): 0s 285.796687ms
Trained!
TypeError: text.split is not a function
    at PunctTokenizer.tokenize (/Users/meshin/projects/console-bot/node_modules/node-nlp/lib/nlp/tokenizers/punct-tokenizer.js:30:17)
    at SentimentAnalyzer.getSentiment (/Users/meshin/projects/console-bot/node_modules/node-nlp/lib/sentiment/sentiment-analyzer.js:118:33)
    at SentimentManager.process (/Users/meshin/projects/console-bot/node_modules/node-nlp/lib/sentiment/sentiment-manager.js:64:38)
    at NlpManager.getSentiment (/Users/meshin/projects/console-bot/node_modules/node-nlp/lib/nlp/nlp-manager.js:287:27)
    at NlpManager.process (/Users/meshin/projects/console-bot/node_modules/node-nlp/lib/nlp/nlp-manager.js:391:35)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by jesus-seijas-sp** [comment]
Hello,

process API accepts 4 parameters:
```javascript
  async process(locale, utterance, srcContext, domainName) {
```

You can call it passing the language and the utterance:
```javascript
  manager.process('en', 'hello');
```

You can call it without passing the language:
```javascript
manager.process('hello');
```

You can provide and undefined language:
```javascript
manager.process(undefined, 'hello');
```

But when you use a context, the contexts is the 3rd parameter, so those are valid:

```javascript
manager.process('en', 'hello', context);
manager.process('hello', undefined, context);
manager.process(undefined, 'hello', context);
```

But this is not valid:
```javascript
manager.process('hello', context);
```
