### ISSUE TITLE
"await" missing in src/nlp.js

### ISSUE THREAD

**Issue by codeforequity-at** [axa-group/nlp.js#353]
**Describe the bug**
This line is missing an _await_:
https://github.com/axa-group/nlp.js/blob/51837c0b7a0b5ba14a93fcf390e4b9a5025fe3da/packages/nlp/src/nlp.js#L356

**To Reproduce**
I am always receiving an UnhandledPromiseRejectionWarning on training

```
(node:9352) UnhandledPromiseRejectionWarning: Error: File cannot be written in web
    at Promise (C:\dev\botium-cli\node_modules\@nlpjs\core\src\mock-fs.js:32:12)
    at new Promise (<anonymous>)
    at Object.writeFile (C:\dev\botium-cli\node_modules\@nlpjs\core\src\mock-fs.js:31:10)
    at Nlp.save (C:\dev\botium-cli\node_modules\@nlpjs\nlp\src\nlp.js:502:14)
    at Nlp.train (C:\dev\botium-cli\node_modules\@nlpjs\nlp\src\nlp.js:356:12)
```

**Comment by jesus-seijas-sp** [comment]
Closing as it was solved
