### ISSUE TITLE
Example Script Bug

### ISSUE THREAD

**Issue by MrPeker** [axa-group/nlp.js#36]
When I try Example Script, getting these error..

 mrpeker@MrPeker-MacBook-Air  ~/Desktop/nlp.js-master/examples/console-bot  node index.js                                                               1 ↵  3354  02:08:15
Say something!
hello
/Users/mrpeker/Desktop/nlp.js-master/examples/console-bot/index.js:51
    if (result.sentiment.score !== 0) {
                         ^

TypeError: Cannot read property 'score' of undefined
    at Interface.rl.on (/Users/mrpeker/Desktop/nlp.js-master/examples/console-bot/index.js:51:26)
    at Interface.emit (events.js:180:13)
    at Interface._onLine (readline.js:285:10)
    at Interface._normalWrite (readline.js:433:12)
    at ReadStream.ondata (readline.js:144:10)
    at ReadStream.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at ReadStream.Readable.push (_stream_readable.js:218:10)
    at TTY.onread (net.js:581:20)

**Comment by jesus-seijas-sp** [comment]
Hello! Good catch! The problem is that process was sync, and we made it async to allow use duckling. 
I already pushed the updated code, to understand the change: https://github.com/axa-group/nlp.js/commit/9306c3fc529044bada6f309160c94aa6d526134e

**Comment by jesus-seijas-sp** [comment]
Solved
