### ISSUE TITLE
TypeError: Cannot read property 'now' of undefined

### ISSUE THREAD

**Issue by yusufola** [axa-group/nlp.js#773]
**Describe the bug**

Whenever I try to train the classifier to get a new model I get the error below on the` classifier.train()`

`TypeError: Cannot read property 'now' of undefined
    at NeuralNetwork.train (/Users/apple/Documents/development/qtab/myqtab-rest-api/node_modules/node-nlp/lib/classifiers/neural-network.js:184:35)
    at BrainClassifier.trainBatch (/Users/apple/Documents/development/qtab/myqtab-rest-api/node_modules/node-nlp/lib/classifiers/brain-classifier.js:73:25)
    at BrainNLU.train (/Users/apple/Documents/development/qtab/myqtab-rest-api/node_modules/node-nlp/lib/nlu/brain-nlu.js:69:29)
    at DomainManager.train (/Users/apple/Documents/development/qtab/myqtab-rest-api/node_modules/node-nlp/lib/nlu/domain-manager.js:192:39)
    at /Users/apple/Documents/development/qtab/myqtab-rest-api/node_modules/node-nlp/lib/nlu/nlu-manager.js:214:50
    at Array.map (<anonymous>)
    at NluManager.train (/Users/apple/Documents/development/qtab/myqtab-rest-api/node_modules/node-nlp/lib/nlu/nlu-manager.js:214:8)
    at NlpManager.train (/Users/apple/Documents/development/qtab/myqtab-rest-api/node_modules/node-nlp/lib/nlp/nlp-manager.js:281:28)
    at NlpService.train (/Users/apple/Documents/development/qtab/myqtab-rest-api/dist/src/nlp/nlp.service.js:105:31)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async NlpService.detectIntent (/Users/apple/Documents/development/qtab/myqtab-rest-api/dist/src/nlp/nlp.service.js:67:17)
    at async NlpService.processMessage (/Users/apple/Documents/development/qtab/myqtab-rest-api/dist/src/nlp/nlp.service.js:55:26)
    at async NlpController.processWhatsapp (/Users/apple/Documents/development/qtab/myqtab-rest-api/dist/src/nlp/nlp.controller.js:27:16)
    at async /Users/apple/Documents/development/qtab/myqtab-rest-api/node_modules/@nestjs/core/router/router-execution-context.js:46:28
    at async /Users/apple/Documents/development/qtab/myqtab-rest-api/node_modules/@nestjs/core/router/router-proxy.js:9:17
`

**Expected behavior**
Train model and create a model file (model.nlp)

**Desktop (please complete the following information):**
 - Framework (Nestjs)

**Additional context**

Here is the method I'm using.

`  async train(context: ConversationContext) {
    this.classifier.addDocument("en", "goodbye for now", "greetings.bye");
    this.classifier.addDocument("en", "bye bye take care", "greetings.bye");
    this.classifier.addDocument("en", "okay see you later", "greetings.bye");
    this.classifier.addDocument("en", "bye for now", "greetings.bye");
    this.classifier.addDocument("en", "i must go", "greetings.bye");
    this.classifier.addDocument("en", "hello", "greetingsHello");
    this.classifier.addDocument("en", "hi %email%", "greetingsHello");
    this.classifier.addDocument("en", "next", "nextLesson");
    this.classifier.addDocument("en", "Next", "nextLesson");

    this.classifier.addDocument(
      "en",
      "send %activationcode% for activation",
      "activateMessagingPlatform"
    );

    this.classifier.addDocument(
      "en",
      "send code %activationcode% for activation",
      "activateMessagingPlatform"
    );

    this.classifier.addDocument(
      "en",
      "%activationcode% for activation",
      "activateMessagingPlatform"
    );

    this.classifier.addDocument(
      "en",
      "send for activation",
      "activateMessagingPlatform"
    );

    // Train also the NLG
    this.classifier.addAnswer("en", "greetings.bye", "Till next time");
    this.classifier.addAnswer("en", "greetings.bye", "see you soon!");
    //hello
    this.classifier.addAnswer("en", "greetingsHello", "Hey there!");
    this.classifier.addAnswer("en", "greetingsHello", "Greetings!");
    this.classifier.addAnswer("en", "greetingsHello", "Hi!");
    this.classifier.addAnswer("en", "nextLesson", "Thanks for responding!\n You should get the next lesson same time tomorrow. See ya! 👋");

    this.classifier.addAnswer(
      "en",
      "activateMessagingPlatform",
      "Activated {{activationcode}}"
    );

    //actions

    // const string = await this.classifier.addRegexEntity("string", "en", /\w/gi);
    const activationcode = await this.classifier.addRegexEntity(
      "activationcode",
      "en",
      /activate:QTAB\S+/
    );

    const number = await this.classifier.addRegexEntity("number", "en", /\d+/g);

    await this.classifier.train();
    await this.classifier.save();
    return;
  }`

**Comment by jesus-seijas-sp** [comment]
From the error I can see things like **BrainClassifier.trainBatch**.
The BrainClassifier does not exists in NLP.js since version 3.x, that was more than 1 year ago even if you are using the last version of the 3.x.
From the version 3.x, 64 new versions were published... 
I'm not giving support for version 3.x anymore.
