### ISSUE TITLE
regex error with slot example

### ISSUE THREAD

**Issue by j2l** [axa-group/nlp.js#93]
**Describe the bug**
copy-pasting-adapting test example for slot throws:
`SyntaxError: Invalid regular expression: /(?<= from )(.*)(?= to )/: Invalid group`

**To Reproduce**
Copy paste [Slot example](https://github.com/axa-group/nlp.js/blob/1fa4c9028820f19411165ebf4e90911d282077b6/examples/microsoft-bot/index.js).
Adapt to use npm package:
```
const { NlpManager } = require('node-nlp');
const modelName = './model.nlp';
const threshold = 0.7;
const nlpManager = new NlpManager();

nlpManager.addLanguage('en');
const fromEntity = nlpManager.addTrimEntity('fromCity');
fromEntity.addBetweenCondition('en', 'from', 'to', { skip: ['travel'] });
fromEntity.addAfterLastCondition('en', 'from', { skip: ['travel'] });
const toEntity = nlpManager.addTrimEntity('toCity');
toEntity.addBetweenCondition('en', 'to', 'from', { skip: ['travel'] });
toEntity.addAfterLastCondition('en', 'to', { skip: ['travel'] });
nlpManager.slotManager.addSlot('travel', 'toCity', true, {
  en: 'Where do you want to go?',
});
nlpManager.slotManager.addSlot('travel', 'fromCity', true, {
  en: 'From where you are traveling?',
});
nlpManager.slotManager.addSlot('travel', 'date', true, {
  en: 'When do you want to travel?',
});
nlpManager.addDocument(
  'en',
  'I want to travel from %fromCity% to %toCity% %date%',
  'travel'
);
nlpManager.addAnswer(
  'en',
  'travel',
  'You want to travel from {{ fromCity }} to {{ toCity }} {{ date }}'
);

if (fs.existsSync(modelName)) {
  nlpManager.load(modelName);
} else {
  //nlpManager.loadExcel(excelName);
  nlpManager.train()
  nlpManager.save(modelName);
}
```
run and you get:
```
E:\disctut\node_modules\node-nlp\lib\ner\regex-named-entity.js:113
    return new RegExp(str.slice(1, index), str.slice(index + 1));
           ^

SyntaxError: Invalid regular expression: /(?<= from )(.*)(?= to )/: Invalid group
    at new RegExp (<anonymous>)
    at Function.str2regex (E:\disctut\node_modules\node-nlp\lib\ner\regex-named-entity.js:113:12)
    at languages.forEach.language (E:\disctut\node_modules\node-nlp\lib\ner\trim-named-entity.js:74:33)
    at Array.forEach (<anonymous>)
    at TrimNamedEntity.addBetweenCondition (E:\disctut\node_modules\node-nlp\lib\ner\trim-named-entity.js:65:15)
    at Object.<anonymous> (E:\disctut\server.js:56:12)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```
BEFORE model is saved.

**Expected behavior**
working bot 😄  
But I guess I messed up again somewhere in my adaptation?

**Additional**
How to add memory slots to XLS?

**Comment by jesus-seijas-sp** [comment]
Well, this is due to previous versions of V8 unable to use regex with ?<=. 
To fix it, install last versions of node 8.x or node 10.x.
And well.. is true, I have to find better way compatible with previous versions of node... :(

**Comment by j2l** [comment]
Ah, ok!
How to add memory slots to XLS?

**Comment by jesus-seijas-sp** [comment]
That's one good feature to ask for! because is not yet done. I'll be honest, is not yet supported because I'm putting more effort on doing a full frontend/backend (react/node) to train chatbots from there, so you can deploy this backend/frontend and manage several chatbots. Of course it will be also open source MIT license.

**Comment by j2l** [comment]
Wow, sounds great!
I'll watch out this too.

Closing this ticket since you offered a solution.
BTW, I have node 10.4.1 but `node -v` throws 8.9.3, go figure. I guess I'll have to reinstall both.
